@startuml App_Open_Sequence
!includeurl dependencies/C4_Container.puml
skinparam sequenceMessageAlign center
skinparam defaultFontName Roboto


actor User
entity NStackClient
entity NStackAPI
database NStackDB
entity AppStoreOrGooglePlay

User -> NStackClient            : Starts app
NStackClient -> NStackAPI       : Sends AppOpen data \n(last_updated, platform, guid, version, old_version)\nIncluding <b>Accept-Language</b> header
NStackAPI -> NStackDB			: Checks to see if the app has been opened <b>X number of times</b>, as set in the NStack Web Console
NStackDB -> NStackAPI			: Returns the <b>Rate reminder</b> to be sent out
NStackAPI -> NStackClient		: Returns the <b>Rate reminder</b> to the client as part of the <b> App Open process </b>
NStackClient -> User			: The <b>Rate reminder dialog</b> is displayed to the user
NStackClient -> NStackClient	: <b> It is up to the developre to construct the rate dialog </b>
User -> NStackClient			: The user aknowledges/dismisses the <b>Rate reminder</b>
User -> AppStoreOrGooglePlay    : Opens App Store or Google Play for the user to rate the app
AppStoreOrGooglePlay ->	User	: The User comes back to the NStackClient app
NStackClient -> NStackAPI		: The <b>Rate reminder</b> is marked as read through a <b>POST</b> request \n <b> {{nstackUrl}}/api/v2/notify/rate_reminder/views </b>
NStackAPI -> NStackDB			: The <b>Rate reminder</b> is marked as read in the NStackDB so it will not be shown in subsequent app openings.

@enduml