@startuml

!include https://raw.githubusercontent.com/nodesagency/plantuml-resources/master/themes/NodesTheme.iuml

title Rate Reminder

actor User
entity app
entity "NStack SDK"
entity "NStack Backend"

User -> app: interacts
app -> "NStack SDK": calls RateReminder.action
"NStack SDK" -> "NStack Backend": sends action

note over "NStack Backend": Is points from received actions\nreach defined threashold\nthe app will be able\nto show rate reminder

app -> "NStack SDK": should rate reminder be shown?
"NStack SDK" -> "NStack Backend": should rate reminder be shown?

alt points from actions reached threashold
    "NStack Backend" -> "NStack SDK": 200
else
    "NStack Backend" -> "NStack SDK": 445
end

alt 200
    "NStack SDK" -> app: true
else
    "NStack SDK" -> app: false
end

alt should show rate reminder
    app -> "NStack SDK": calls RateReminder.show
    "NStack SDK" -> User: shows rate reminder dialog
    User -> "NStack SDK": selects an option from dialog
    "NStack SDK" -> "NStack Backend": selected option
    "NStack SDK" -> app: selected option
    alt user pressed positive button (action "positive")
        app -> User: redirects to play store
    else user pressed negative button (action "negative")
        app -> User: redirects to feedback screen
        User -> app: feedback
        app -> "NStack SDK": calls Feedback.send
        "NStack SDK" -> "NStack Backend": feedback
    end
end

@enduml
